name: Continuous Integration

on:
  push:
    branches:
    - master
    
jobs:
  compile:
    
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v2.3.3
      - name: Setting up node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
      - name: Creating new semantic version
        id: create_version
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          WITH_V: true
      - name: Generating Resourcepack
        run: node src/generate.js
        env:
          GITHUB_RELEASE_VERSION: ${{ steps.create_version.outputs.new_tag }}
      - name: Zipping Resources
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -r ./resourcepack.zip ./assets ./pack.mcmeta ./LICENSE ./pack.png
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
        # Artifact name
          name: pack
        # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
          path: ./resourcepack.zip
        # The desired behavior if no files are found using the provided path.
        # Available Options:
        #  warn: Output a warning but do not fail the action
        #  error: Fail the action with an error message
        #  ignore: Do not output any warnings or errors, the action does not fail

          if-no-files-found: warn # optional, default is warn
          # Duration after which artifact will expire in days. 0 means using default retention. Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
          retention-days: 0 # optional
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: models
          path: ./item-models.yml
  
